--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2023-01-20 00:55:18
with Taste_Basictypes;        use Taste_Basictypes;
with Taste_Workshop_Dataview; use Taste_Workshop_Dataview;
with adaasn1rtl;
with Interfaces.C.Strings; use Interfaces.C.Strings;

package Tmtc_Handler_RI is

   procedure Deploy_Parachute;
   
   
   procedure Get_Acceleration (Acceleration : out asn1SccAcceleration);
   
   
   procedure Get_Altitude (Altitude : out asn1SccAltitude);
   
   
   procedure Get_Velocity (Velocity : out asn1SccVelocity);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "tmtc_handler_check_queue";

   --  Return the SDL state as a char * for the MSC tracing function
   function To_C_Pointer (State_As_String : String) return Chars_Ptr is
      (Null_Ptr);  --  Implemented only for Linux/native platforms due to malloc
end Tmtc_Handler_RI;
