/* Header file for function parachute_deployer
 * Generated by TASTE on 2023-01-20 00:55:18
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void parachute_deployer_startup(void);

/* Provided interfaces */
void parachute_deployer_PI_deploy_parachute( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
