/* Body file for function parachute_deployer
 * Generated by TASTE on 2023-01-20 00:55:18
 * You can edit this file, it will not be overwritten
 * Provided interfaces : deploy_parachute
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "parachute_deployer.h"
//#include <stdio.h>


void parachute_deployer_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[parachute_deployer] Startup");
}

void parachute_deployer_PI_deploy_parachute(void)
{
   // Write your code here
}


